---
title: "Publications"
---

# Journal Articles

1.	I. Mahmud, M. Mustapha, S. H. Sulaiman, I. Abdulwahab, I. A. Shehu, **A. J. Aliyu**, Y. S. Abu, N. A. Iliyasu, “Solar Irradiance Forecast using Feed Forward Neural Network: A Case Study of Zaria Town,” FUDMA Journal of Engineering and Technology, vol. 1, no. 2, pp. 167–172, 2025.
2.	D. E. Abah, Y. Sani Abu, M. A. Ndalami, **A. J. Aliyu**, and N. A. Iliyasu, “Efficient energy management for hybrid power systems using Fuzzy Logic Controller Corresponding Author,” KIU Journal of Science, Engineering and Technology, vol. 4, no. 1, pp. 176–181, 2025, doi: 10.59568/KJSET-2025-4-1-18.
3.	S. H. Sulaiman, S. Ebenezer, I. Abdulwahab, I. Mahmud, N. A. Iliyasu, and **A. J. Aliyu**, “Impacts of electrode geometry and gap length on the breakdown voltage of insulating liquids,” KIU Journal of Science, Engineering and Technology, vol. 4, no. 1, pp. 134–141, Apr. 2025, doi: 10.59568/KJSET-2025-4-1-13.
4.	**A. J. Aliyu**, R. Kannan, and H. T. Wei, “Impact of grid strength on grid-forming inverter performance: a comparative study of droop and virtual synchronous generator controls,” Engineering Research Express, vol. 7, no. 2, p. 025340, Jun. 2025, doi: 10.1088/2631-8695/add2d4.  
5.	**A. J. Aliyu** and R. Kannan, “Comprehensive review of fault ride-through techniques for grid-forming inverters: current approaches, challenges, and future directions,” Engineering Research Express, vol. 7, no. 2, p. 022302, Jun. 2025, doi: 10.1088/2631-8695/adc98e.  
6.	Jada, A. M., Abdulkarim, A., Mohammed, M., Seidu, I., & **Aliyu, A. J.** (2024). Optimizing PV Power Production by Incremental Conductance and Model Predictive Control Maximum Power Point Tracking Technique. Savannah Journal of Science and Engineering Technology, 2(5), 203–213.
7.	Iliyasu, N., Ahmed, A., Abah, D., **Aliyu, A. J.**, Abdulwahab, I., & Musbahu, D. (2024). Optimal Design of a Hybrid Renewable Energy System as a Substitute Power Source for HAFEDPOLY Kazaure. ATBU Journal Of Science, Technology And Education, 12(2), 375-388.
8.	David Enemali Abah, Ibrahim Abdullahi Shehu, **Aminu Jibrin Aliyu**, Nuraddeen Adam Iliyasu (2023) Moth Flame Optimization for Optimal Sizing and Placement of Distributed Energy Systems. Zaria Journal of Electrical Engineering Technology, 12(1), 25-34. 
9.	Hassan, M. S., Abubakar, A. S., Salisu, S., **Aliyu, A. J.**, & Almustapha, M. D.  (2022) Modeling and Implementation of a Self-Tuning Adaptive Controller of an Inverter in a Grid-connected Microgrid. Nigerian Journal of Engineering, 29 (3), 1-5. 
10.	**Aliyu AJ**, Abubakar AS, Kunya AB, Salisu S. Harmonics Mitigation Using Delta Connected Cascaded H-Bridge Based Active Power Filter. Nigerian Journal of Engineering, 28 (3), 70-74.


# Conference Proceedings Papers 
11.	**A. J. Aliyu**, R. Kannan, H. T. Wei, D. E. Abah, R. M. A. Jani and N. G. M. Thao, "Analysis of Dynamic Response of VSG-Controlled Grid-Forming Inverter Under Fault Conditions," 2026 IEEE 2nd International Conference on Consumer Technology (ICCT-Pacific), Yoshida, Yamaguchi-shi, Japan, 2026, pp. 27-30, doi: 10.1109/ICCT-Pacific69083.2026.11518692.
12.	I. Abdulwahab, **A. J. Aliyu**, P. E. Peter, Y. S. Abu, D. E. Abah, and N. A. Iliyasu, “Piezoelectric Foot Mat Energy Harvesting for Low-Power Applications: Exploring the Impact of Weight Distribution and Step Frequency,” Applied Mechanics and Materials, vol. 935, pp. 143–152, Apr. 2026, doi: 10.4028/p-QUO3wf.
13.	S. A. Ahmad, A. Bature, and **A. J. Aliyu**, “Time Series Energy Demand Forecast Using ANN Model Considering Various Influencing Meteorological and Economic Factors in Kano State, Nigeria,” J Phys Conf Ser, vol. 3191, no. 1, p. 012066, Apr. 2026, doi: 10.1088/1742-6596/3191/1/012066.
14.	N. A. Iliyasu, **A. J. Aliyu**, K. F. Omeiza, H. Mustapha, S. H. Sulaiman, D. E. Abah, and A. S. Musa, “Real-Time Adaptive Differential Scheme for Enhanced Transformer Protection,” 2nd International Conference on Electrical Engineering Applications (ICEEA'2025), Zaria, Kaduna, Nigeria, 2025, pp 152-155.
15.	L. J. Aliyu, M. S. Hassan, **A. J. Aliyu** and S. T. Shehu, “Vision Transformers for Diabetic Retinopathy Detection: Towards Accessible Screening in Resource-Constrained Settings,” 2nd International Conference on Electrical Engineering Applications (ICEEA'2025), Zaria, Kaduna, Nigeria, 2025, pp 347-350.
16.	I. Abdulwahab, N. A. Iliyasu, E. K. Rasaq, **A. J. Aliyu**, M. M. Hasan and R. Kannan, "Optimized Unified Power Quality Conditioner for Nonlinear Load Connected Microgrid Using Artificial Rabbit Search Optimization," 2025 IEEE Industrial Electronics and Applications Conference (IEACon), Kota Kinabalu Sabah, Malaysia, 2025, pp. 143-147, doi: 10.1109/IEACon64690.2025.11254146.
17.	M. M. Hasan, R. Kannan, **A. J. Aliyu**, H. R. L, K. Porkumaran, and V. Jain, “Analysis of SoC Prediction Accuracy for Samsung INR21700 Li-ion Battery Using Pelican Optimized Bilstm Network,” in 2025 IEEE 15th International Conference on Power Electronics and Drive Systems (PEDS), IEEE, Jul. 2025, pp. 1–5. doi: 10.1109/PEDS63958.2025.11144843.
18.	I. Abdulwahab, S. H. Sulaiman, I. Mahmud, I. A. Shehu, A. Habeeb, **A. J. Aliyu** and A. Olaniyan (2025). Development of an Effective Dust removal System for Solar Panels to increase Energy Efficiency. 3rd Faculty of Engineering and Technology Conference (FETiCON 2025), Ilorin, Nigeria. pp 65-69
19.	Sulaiman, S. H., Mahmud, I., Abubakar, A., Abdulwahab, I., Sani, A., Shehu, I. A., **Aliyu A. J.**, & Musa, A. S. (2024). Optimal Capacitor Sizing and Siting in a Radial Distribution System Using Particle Swam Optimization Algorithm. 2024 IEEE 5th International Conference on Electro-Computing Technologies for Humanity (NIGERCON), 1–5. https://doi.org/10.1109/NIGERCON62786.2024.10927092
20.	**A. J. Aliyu**, R. Kannan and H. T. Wei, "Investigation of the Impact of Control Parameter on Virtual Synchronous Generator-Based Grid-Forming Inverters for Enhanced Power System Stability," 2024 IEEE International Conference on Power and Energy (PECon), Kuala Lumpur, Malaysia, 2024, pp. 92-97, doi: 10.1109/PECon62060.2024.10827664. 
21.	E. S. Siew Wei, N. Kumar, R. Kannan, **A. J. Aliyu**, A. A and A. S. Arockia Doss, "Optimizing Solar PV System Performance Using Feedforward Neural Network Control Algorithm," 2024 IEEE Industrial Electronics and Applications Conference (IEACon), Kuala Lumpur, Malaysia, 2024, pp. 146-151, doi: 10.1109/IEACon61321.2024.10797448. 
22.	**Aliyu, A. J**, Iliyasu, N. A & D. E. Abah. (2024). Harmonic Distortion in PV Systems: A Comparative Study of PID and ANN Controllers. 2nd Faculty of Engineering and Technology Conference (FETiCON 2024), Ilorin, Nigeria. pp 65-69.
23.	Abah, D. E., Iliyasu, N. A., **Aliyu, A. J.**, & Kabir, A. (2023). Design and Simulation of Hybrid Power Supply for Residential Consumer. 1st Faculty of Engineering and Technology Conference (FETiCON 2023), Ilorin, Nigeria. pp 463–482.
24.	**Aliyu, A. J.**, Saidu, A. A., Kunya, A. B., & Salisu, S. (2022). Development of Active Power Filter Based on Delta Connected Cascaded H-Bridges. 1st International Conference on Scientific and Academic Research, 50–54.
